
   
FROM balenalib/%%BALENA_MACHINE_NAME%%-node:16

WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY ./server ./server
RUN npm i
RUN pwd && ls -al && ls -al server

CMD ["npm", "start"]