FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-node:16

WORKDIR /usr/src/app

# install build packages
RUN apk --no-cache add python2 python3 py3-pip make g++

# install node dependencies
COPY package.json package-lock.json ./
RUN npm i

# copy app
COPY ./db ./db
COPY ./server ./server

# run app
CMD ["npm", "start"]
